---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- with .Values.finenomore.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.finenomore.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.finenomore.name }}
          image: {{ .Values.finenomore.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  {{- with .Values.finenomore.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.finenomore.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.finenomore.name }}
              port:
                number: 80